
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Blog : Homepage</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css"
   integrity="sha384-QYIZto+st3yW+o8+5OHfT6S482Zsvz2WfOzpFSXMF9zqeLcFV0/wlZpMtyFcZALm" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
   integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,600;1,600&display=swap"
   rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
   integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="../../../public/assets/css/style.css">
</head>

<body>


  <?php
  echo "<nav class='navbar'>
          <img src='../assets/images/logo.png' class='logo' alt=''>
          <ul class='links-container'>";
  if (isset($_COOKIE['login'])) {
    echo "<li class='link-item'><a href='/login/logout' class='link'>logout</a></li>";
    echo "<li class='link-item'><a href='/index/home' class='link'>Home</a></li>";
    echo "<li class='link-item'><a href='/blog/myblog' class='link'>My Blogs</a></li>";
    echo "<li class='link-item'><a href='/admin/adminblog' class='link'>Admin</a></li>";
  } else {
    echo "<li class='link-item'><a href='/signup/' class='link'>Login</a></li>";
    echo "<li class='link-item'><a href='/index/home' class='link'>Home</a></li>";
  }
  ?>

  </ul>
  </nav>

  <!-- slideshow -->
  <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="10000">
        <img src="../../../public/assets/images/header.png" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item" data-bs-interval="1000">
        <img src="../../../public/assets/images/header.png" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="../../../public/assets/images/header.png" class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <br>
  <!-- end slideshow -->
  <!-- button to start writinh your own blog -->
  <?php

  if (isset($_COOKIE['login'])) {
    echo "<div class='text-center'>
  <button type='button' class='btn btn-secondary'><a href='/blog/index' class='link'>Create</a></button>
</div>";
  }

  ?>

  <!-- blog section -->
  <?php
  $count = 0;
  echo " <section class='blogs-section'>";
  foreach ($result as  $value) {

    echo "<div class='blog-card'>";
    echo "<img src='" . $value->image . "' class='blog-image' alt='' width='50%'/>";
    echo "<h1 class='blog-title'>" . $value->topic . "</h1>";
    echo "<p class='blog-overview'>" .$value->data . "</p>";
    echo "<a href='/index/fullblog?id=" . $value->id . "' class='btn btn-dark'>read</a>&nbsp&nbsp";
    echo "<i class='fa-solid fa-heart'>
    </i></div></br>";
  }
  echo "</section>";
  ?>
  </section>
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
<script src="../assets/js/script.js"></script>
</html>